import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Loader2, Megaphone, RefreshCw, Send, UsersRound } from 'lucide-react';
import { supabase } from '../supabaseClient';

type Pipeline = { id: string; name: string };
type Stage = { id: string; pipeline_id: string; name: string };
type Template = { id: string; name: string; language: string; status: string; components?: Array<{ type: string; text?: string }> };
type Campaign = { id: string; name: string; template_name: string; status: string; total_recipients: number; sent_count: number; failed_count: number; created_at: string };
const variableOptions = [{ value: 'patient_name', label: 'Nome do paciente' }, { value: 'seller_name', label: 'Responsavel comercial' }, { value: 'opportunity_title', label: 'Oportunidade' }, { value: 'amount', label: 'Valor da oportunidade' }];

async function headers() { const { data: { session } } = await supabase.auth.getSession(); if (!session) throw new Error('Sessao expirada.'); return { Authorization: `Bearer ${session.access_token}`, 'Content-Type': 'application/json' }; }

export const WhatsAppBulkCampaigns: React.FC = () => {
  const [pipelines, setPipelines] = useState<Pipeline[]>([]); const [stages, setStages] = useState<Stage[]>([]); const [templates, setTemplates] = useState<Template[]>([]); const [campaigns, setCampaigns] = useState<Campaign[]>([]);
  const [pipelineId, setPipelineId] = useState(''); const [stageId, setStageId] = useState(''); const [templateKey, setTemplateKey] = useState(''); const [name, setName] = useState(''); const [mapping, setMapping] = useState<Record<number, string>>({}); const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false); const [notice, setNotice] = useState<{ type: 'success' | 'error'; text: string } | null>(null);
  const load = useCallback(async () => {
    const requestHeaders = await headers();
    const [pipelineResult, stageResult, templatesResult, campaignsResult] = await Promise.all([supabase.from('clinic_experts_pipelines').select('id,name').order('name'), supabase.from('clinic_experts_stages').select('id,pipeline_id,name').order('position'), fetch('/api/integrations/whatsapp/templates', { headers: requestHeaders }), fetch('/api/integrations/whatsapp/bulk-campaigns', { headers: requestHeaders })]);
    if (pipelineResult.error || stageResult.error) throw pipelineResult.error || stageResult.error;
    const templateBody = await templatesResult.json(); const campaignBody = await campaignsResult.json(); if (!templatesResult.ok) throw new Error(templateBody.error || 'Nao foi possivel consultar os templates.'); if (!campaignsResult.ok) throw new Error(campaignBody.error || 'Nao foi possivel consultar as campanhas.');
    setPipelines((pipelineResult.data || []) as Pipeline[]); setStages((stageResult.data || []) as Stage[]); setTemplates((templateBody.templates || []).filter((item: Template) => item.status === 'APPROVED')); setCampaigns(campaignBody.campaigns || []); setPipelineId(current => current || pipelineResult.data?.[0]?.id || '');
  }, []);
  useEffect(() => { load().catch(error => setNotice({ type: 'error', text: error.message || 'Falha ao carregar.' })).finally(() => setLoading(false)); }, [load]);
  const selectedTemplate = templates.find(item => `${item.name}::${item.language}` === templateKey); const body = selectedTemplate?.components?.find(item => item.type === 'BODY')?.text || ''; const positions = useMemo(() => Array.from(new Set(Array.from(body.matchAll(/\{\{(\d+)\}\}/g), item => Number(item[1])))).sort((a, b) => a - b), [body]); const visibleStages = stages.filter(item => item.pipeline_id === pipelineId);
  const variableMapping = positions.map(position => `{{${position}}} = ${mapping[position] || ''}`).filter(line => !line.endsWith('= ')).join('\n');
  const createCampaign = async () => {
    if (!name.trim() || !pipelineId || !selectedTemplate) return setNotice({ type: 'error', text: 'Informe o nome, funil e template aprovado.' });
    if (positions.some(position => !mapping[position])) return setNotice({ type: 'error', text: 'Mapeie todas as variaveis do template.' });
    if (!window.confirm('Confirmar o inicio desta campanha? O envio sera feito apenas para os contatos com telefone valido no filtro escolhido.')) return;
    setSending(true); setNotice(null);
    try { const requestHeaders = await headers(); const response = await fetch('/api/integrations/whatsapp/bulk-campaigns', { method: 'POST', headers: requestHeaders, body: JSON.stringify({ name: name.trim(), templateName: selectedTemplate.name, language: selectedTemplate.language, variableMapping, pipelineId, stageId }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Falha ao criar campanha.');
      let pending = result.totalRecipients; let sent = 0; let failed = 0;
      while (pending > 0) { const process = await fetch('/api/integrations/whatsapp/bulk-campaigns', { method: 'POST', headers: requestHeaders, body: JSON.stringify({ action: 'process', campaignId: result.campaignId }) }); const batch = await process.json(); if (!process.ok) throw new Error(batch.error || 'Falha durante o envio.'); pending = batch.pending; sent += batch.sent; failed += batch.failed; }
      setNotice({ type: 'success', text: `Campanha concluida: ${sent} enviado(s)${failed ? `, ${failed} com falha` : ''}.` }); setName(''); await load();
    } catch (error) { setNotice({ type: 'error', text: error instanceof Error ? error.message : 'Falha na campanha.' }); await load(); } finally { setSending(false); }
  };
  if (loading) return <div className="flex h-full items-center justify-center gap-2 text-sm text-[var(--text-muted)]"><Loader2 className="h-4 w-4 animate-spin" /> Carregando campanhas</div>;
  return <div className="custom-scrollbar h-full overflow-y-auto bg-[var(--bg)] px-4 py-5 text-[var(--text)] sm:px-6 lg:px-8"><div className="mx-auto max-w-[1180px]"><header className="flex flex-col gap-3 border-b border-[var(--border)] pb-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-2 flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.16em] text-[var(--primary)]"><Megaphone className="h-4 w-4" /> WhatsApp Business</div><h1 className="text-2xl font-bold tracking-[-.03em]">Disparador em massa</h1><p className="mt-1 text-sm text-[var(--text-secondary)]">Envie somente templates aprovados pela Meta para os contatos do funil selecionado. Numeros duplicados entram apenas uma vez.</p></div><button type="button" onClick={() => void load()} className="flex h-9 items-center justify-center gap-2 rounded-lg border border-[var(--border)] px-3 text-xs font-semibold hover:bg-[var(--bg-subtle)]"><RefreshCw className="h-3.5 w-3.5" /> Atualizar</button></header>
    {notice && <div className={`mt-5 rounded-xl border px-4 py-3 text-sm ${notice.type === 'success' ? 'border-emerald-200 bg-emerald-50 text-emerald-800' : 'border-rose-200 bg-rose-50 text-rose-700'}`}>{notice.text}</div>}
    <section className="mt-5 grid gap-5 lg:grid-cols-[minmax(0,1fr)_340px]"><div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="mb-5 flex items-center gap-2"><UsersRound className="h-4 w-4 text-[var(--primary)]" /><h2 className="text-sm font-bold">Nova campanha</h2></div><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-semibold">Nome da campanha<input value={name} onChange={event => setName(event.target.value)} placeholder="Ex.: Retomada de setembro" className="mt-2 h-10 w-full rounded-lg border border-[var(--border)] bg-[var(--bg-subtle)] px-3 text-sm font-normal outline-none focus:border-[var(--primary)]" /></label><label className="text-xs font-semibold">Funil<select value={pipelineId} onChange={event => { setPipelineId(event.target.value); setStageId(''); }} className="mt-2 h-10 w-full rounded-lg border border-[var(--border)] bg-[var(--bg-subtle)] px-3 text-sm font-normal"><option value="">Selecione</option>{pipelines.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-xs font-semibold">Etapa <span className="font-normal text-[var(--text-muted)]">(opcional)</span><select value={stageId} onChange={event => setStageId(event.target.value)} className="mt-2 h-10 w-full rounded-lg border border-[var(--border)] bg-[var(--bg-subtle)] px-3 text-sm font-normal"><option value="">Todas as etapas</option>{visibleStages.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-xs font-semibold">Template aprovado<select value={templateKey} onChange={event => { setTemplateKey(event.target.value); setMapping({}); }} className="mt-2 h-10 w-full rounded-lg border border-[var(--border)] bg-[var(--bg-subtle)] px-3 text-sm font-normal"><option value="">Selecione</option>{templates.map(item => <option key={`${item.name}::${item.language}`} value={`${item.name}::${item.language}`}>{item.name} ({item.language})</option>)}</select></label></div>
      {selectedTemplate && <div className="mt-5 rounded-xl border border-[var(--border)] bg-[var(--bg-subtle)] p-4"><p className="text-[10px] font-bold uppercase tracking-wide text-[var(--text-muted)]">Previa do template</p><p className="mt-2 whitespace-pre-wrap text-sm leading-relaxed text-[var(--text-secondary)]">{body || 'Este template nao possui texto no corpo.'}</p>{positions.length > 0 && <div className="mt-4 grid gap-3 sm:grid-cols-2">{positions.map(position => <label key={position} className="text-xs font-semibold">Variavel {`{{${position}}}`}<select value={mapping[position] || ''} onChange={event => setMapping(current => ({ ...current, [position]: event.target.value }))} className="mt-1.5 h-9 w-full rounded-lg border border-[var(--border)] bg-[var(--surface)] px-2 text-xs font-normal"><option value="">Mapear campo</option>{variableOptions.map(item => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>)}</div>}</div>}
      <button type="button" disabled={sending} onClick={() => void createCampaign()} className="mt-5 flex h-10 items-center gap-2 rounded-lg bg-[var(--primary)] px-4 text-xs font-bold text-white transition hover:brightness-95 active:translate-y-px disabled:cursor-not-allowed disabled:opacity-50">{sending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}{sending ? 'Enviando lotes...' : 'Confirmar e iniciar campanha'}</button></div>
      <aside className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="text-sm font-bold">Historico recente</h2><div className="mt-4 divide-y divide-[var(--border)]">{campaigns.length ? campaigns.map(item => <div key={item.id} className="py-3"><div className="flex items-start justify-between gap-2"><p className="text-xs font-semibold">{item.name}</p><span className="rounded-md bg-[var(--bg-subtle)] px-2 py-1 text-[10px] font-bold uppercase text-[var(--text-secondary)]">{item.status}</span></div><p className="mt-1 text-[11px] text-[var(--text-muted)]">{item.template_name} · {item.sent_count}/{item.total_recipients} enviados{item.failed_count ? ` · ${item.failed_count} falhas` : ''}</p></div>) : <p className="py-5 text-xs text-[var(--text-muted)]">Nenhuma campanha criada.</p>}</div></aside></section></div></div>;
};
