
export enum Tab {
  FINANCIAL = 'Financeiro',
  ORTHODONTICS = 'Ortodontia',
  LABWORK = 'Laboratório',
  MEETINGS = 'Gestão & Comercial',
  SUPPORT = 'Chamados',
  PASSWORDS = 'Senhas',
  RESPONSIBILITIES = 'Responsabilidades',
  BIBLIOTECA = 'Biblioteca',
  TASKS = 'Tarefas',
  CRM = 'CRM'
}

export interface UserProfile {
  id: string;
  email: string;
  role: 'admin' | 'user' | 'reception';
  allowed_tabs: string[];
  allowed_sub_tabs?: string[];
}

export interface Transaction {
  id: string;
  date: string;
  settlementDate?: string; 
  description: string;
  subDescription?: string;
  category: string;
  supplier?: string;
  type: 'income' | 'expense';
  amount: number;
  status: 'Paid' | 'Pending' | 'Overdue';
  paymentMethod: string;
  professional?: string;
  installments?: number;
  accountId?: string;
  reconciliationStatus?: 'verified' | 'error' | 'pending';
  reconciliationNote?: string;
  invoiceEmitted?: boolean;
  isPartial?: boolean;
  appliedFeeRate?: number;
  explicitFeeAmount?: number;
  observation?: string;
  cardBrand?: string;
  isRecurrent?: boolean;
  totalRecurrences?: number;
  recurrenceIndex?: number;
  parentTransactionId?: string;
  isAutoGenerated?: boolean;
  externalId?: string; // ID do sistema externo (UUID)
  source?: string;     // Origem da integração (ex: 'API_EXTERNA')
  salesTeam?: string;
}

export interface Account {
  id: string;
  name: string;
  bank: string;
  type: string;
  balance: number;
  color: string;
  initialBalance?: number;
  futureBalance?: number;
}

export interface LabPayment {
  id: string;
  orderId: string;
  paymentDate: string;
  amount: number;
  method: string;
  notes?: string;
}

export interface LabOrder {
  id: string;
  patientName: string;
  proteseId?: string; 
  details: string; 
  type: string; 
  status: 'Moldagem' | 'Provas' | 'Concluido' | 'Entregue';
  startDate: string;
  dueDate: string;
  cost: number;
  saleValue: number;
  labName: string;
  icon?: string;
  payments?: LabPayment[];
}

export interface ActionItem {
  id: string;
  task: string;
  owner: string;
  done: boolean;
  deadline?: string;
}

export interface Meeting {
  id: string;
  title: string;
  date: string;
  participants: string[];
  content: string;
  actionItems: ActionItem[];
  tags: string[];
  history?: {date: string, entry: string}[];
}

export interface SupportTicket {
  id: string;
  title: string;
  description: string;
  category: 'Sistema' | 'Operacional' | 'Manutencao' | 'Outros';
  priority: 'Baixa' | 'Media' | 'Alta' | 'Critica';
  status: 'Aberto' | 'Em Andamento' | 'Resolvido';
  createdAt: string;
  createdBy?: string;
}

export interface Responsibility {
  id: string;
  userEmail: string;
  title: string;
  description: string;
  periodicity: 'daily' | 'weekly' | 'monthly' | 'occasional';
  status: 'pending' | 'completed';
  createdAt: string;
  updatedAt: string;
}

export interface AppNotification {
  id: string;
  userId?: string;
  title: string;
  message: string;
  type: 'deadline' | 'lab' | 'message' | 'system';
  priority: 'low' | 'medium' | 'high' | 'urgent';
  isRead: boolean;
  link?: string;
  tab?: Tab;
  createdAt: string;
}

export interface ChatMessage {
  id: string;
  content: string;
  senderId: string;
  senderName: string;
  timestamp: string;
}

export interface ThirdPartyCost {
  id: string;
  name: string;
  cost: number;
}

export interface Service {
  id: string;
  name: string;
  defaultValue: number;
  fichaMaterials?: { materialId: string; quantity: number }[];
  thirdPartyCosts?: ThirdPartyCost[];
}

export interface Product {
  id: string;
  name: string;
  cost: number;
}
